"""Crawl-error taxonomy + per-status policy — single source of truth for
'what went wrong' (reason strings) and 'what to do about it' (policy verbs).

Reason strings are the keys of the per-job ``errors_by_reason`` summary and are
persisted in CrawlHistory. HTTP failures use ``"http_<status>"`` verbatim so the
per-status breakdown is free; non-HTTP categories are the constants below.

Nothing here imports the rest of the crawler package (no circular deps) — it is
pure classification + policy tables, consumed by fetcher/async_engine/harvest.
"""
from __future__ import annotations

import os

# ── reason vocabulary (errors_by_reason keys; also stored in sqlite) ──────────
DNS = "dns"
SSL = "ssl"                         # cert/handshake — NEVER bypassed (see classify note)
CONN_REFUSED = "conn_refused"
TIMEOUT = "timeout"
RENDER_CRASH = "render_crash"
PARSE_ERROR = "parse_error"
TOO_LARGE = "too_large"
ROBOTS = "blocked_by_robots"
HOST_DOWN = "skipped_host_down"     # circuit breaker tripped this run
GONE_SKIP = "skipped_gone"          # known-404/410 from a prior run
OFF_PEAK = "skipped_off_peak"       # careful host, outside its allowed crawl window
TRAP = "trap"                       # frontier heuristic drop (not a fetch error)
# A 4xx that a full human-like Playwright session STILL couldn't clear — needs a
# different network path (residential proxy / real headless session / source API),
# not another retry. Routed here so these are queryable instead of blending into http_403.
NEEDS_NETWORK_PATH = "needs_network_path"
# Live host was WAF-blocked but we served the content from the Wayback Machine's
# archived copy instead — a SUCCESS via a WAF-free path, tagged so the dashboard
# shows "routed around the block" distinctly from a raw fetch.
SERVED_FROM_ARCHIVE = "served_from_archive"
# Live host was WAF-blocked but the CamoFox stealth engine (C3) rendered it —
# a SUCCESS via engine-level fingerprint spoofing, distinct from a raw fetch.
SERVED_BY_CAMOFOX = "served_by_camofox"
# Live host TLS-fingerprint-blocked plain httpx, but a curl_cffi real-Chrome JA3 GET cleared it —
# a SUCCESS via a cheap impersonated fetch that skipped the browser/C3 escalation entirely.
SERVED_BY_IMPERSONATE = "served_by_impersonate"
# The fallback reason: classify_failure() returns this when nothing else matched.
OTHER = "other"
# Captcha / solver reason codes (C3 solver integration)
CAPTCHA_SOLVED = "captcha_solved"
CAPTCHA_FAILED = "captcha_failed"
NEEDS_CAPTCHA_SOLVER = "needs_captcha_solver"


# A CDN IP-reputation block page served with HTTP 200 (Akamai "Access Denied" etc.). C3 forces
# status=200 on any render, so the BODY is the only signal that the stealth render actually got
# blocked at the IP layer rather than delivering real content.
_IP_BLOCK_MARKERS = ("access denied", "edgesuite.net",
                     "you don't have permission to access", "reference #")

# Phrases distinctive enough that ONE is proof — they don't occur in editorial prose. The weak
# markers above are Akamai-shaped and matched none of CloudFront's wall, which is why 709 CloudFront
# "403 ERROR / Request blocked" pages were stored as real documents (lockheedmartin, boeing, mbda,
# bel-india): CloudFront serves that body with HTTP **200**, so the status check never fired.
_BLOCK_PAGE_STRONG = (
    "the request could not be satisfied",            # CloudFront 403 wall
    "generated by cloudfront",
    "enable javascript and cookies to continue",      # Cloudflare interstitial
    "attention required! | cloudflare",
    "checking your browser before accessing",
    "verify you are human by completing the action",
)


def is_ip_block_page(rendered: str | None) -> bool:
    """True if a rendered body is really a CDN IP-block page (Akamai 'Access Denied' etc.), not
    content. Title match, or >=2 markers — one marker alone would false-hit an article that merely
    mentions e.g. 'access denied'. Used to (a) stop counting a blocked C3 render as a success and
    (b) trigger a fresh-IP retry."""
    if not rendered:
        return False
    low = rendered.lower()
    return ("<title>access denied</title>" in low
            or any(m in low for m in _BLOCK_PAGE_STRONG)
            or sum(m in low for m in _IP_BLOCK_MARKERS) >= 2)


# A rendered anti-bot CHALLENGE / CAPTCHA interstitial — distinct from a plain IP block. These are
# walls a captcha solver or a better browser fingerprint might clear (so they flag as a captcha
# limitation, not needs_network_path). Distinctive enough that one is proof: none occur in prose.
# CRITICAL: markers must be ACTIVE-wall signals only — text/scripts that are gone once the challenge
# is passed. Widget SCRIPT sources (challenges.cloudflare.com/turnstile, hcaptcha.com/, recaptcha/)
# and the response FIELDS (cf-turnstile-response) stay in the DOM AFTER a pass, so keying on them made
# is_captcha_wall fire on the very page that proves success — measured on
# scrapingcourse.com/cloudflare-challenge, whose "You bypassed the Cloudflare challenge!" page still
# references challenges.cloudflare.com/turnstile and was therefore recorded as needs_captcha_solver.
# Keep only the interstitial text + the managed-challenge orchestrate path, which are absent post-pass.
_CAPTCHA_WALL_MARKERS = (
    "just a moment", "/cdn-cgi/challenge-platform", "cf-chl-",
    "checking your browser before accessing", "attention required! | cloudflare",
    "verify you are human", "verifying you are human", "enable javascript and cookies to continue",
    "px-captcha", "_incapsula_resource", "captcha-delivery.com/captcha",
    "please complete the security check", "pardon our interruption",
)


def is_captcha_wall(rendered: str | None) -> bool:
    """True if a rendered body is an anti-bot CHALLENGE / CAPTCHA interstitial (Cloudflare managed
    challenge, Turnstile, reCAPTCHA/hCaptcha, DataDome, Imperva…). Used so a wall C3 could not clear
    is flagged as a captcha LIMITATION (resolvable with a solver / better fingerprint) rather than a
    generic IP block — the operator asked for that distinction, with the URL kept in a log."""
    if not rendered:
        return False
    low = rendered.lower()
    return any(m in low for m in _CAPTCHA_WALL_MARKERS)


def http_reason(status: int) -> str:
    return f"http_{status}"


def _env_int(k: str, d: int) -> int:
    return int(os.environ.get(k, str(d)))


# ── policy verbs ──────────────────────────────────────────────────────────────
DROP = "drop"              # count, move on
GONE = "gone"              # persist as permanently gone (skip on future runs)
DISGUISE = "disguise"      # one retry with a browser UA (403 only — UA spoof is the ceiling)
RETRY_LATER = "retry_later"  # transient: one in-run requeue + next-run eligible
COOLDOWN = "cooldown"      # RETRY_LATER + put the whole host on cooldown (429/503)

_STATUS_POLICY = {
    400: DROP, 401: DROP, 403: DISGUISE, 404: GONE, 410: GONE,
    429: COOLDOWN, 500: RETRY_LATER, 502: RETRY_LATER, 503: COOLDOWN, 504: RETRY_LATER,
}


def policy_for_status(status: int) -> str:
    if status in _STATUS_POLICY:
        return _STATUS_POLICY[status]
    return RETRY_LATER if status >= 500 else DROP


# categories that feed the per-host circuit breaker (a dead HOST, not a bad page)
HARD_FAIL = {DNS, CONN_REFUSED, SSL}
# categories eligible for an in-run requeue (transient — the page itself may recover)
TRANSIENT = {TIMEOUT, RENDER_CRASH}
# Weakness-under-load signature (the SIPRI case): a host that refuses/resets/times-out when hit at
# high concurrency should be auto-slowed to careful (conc 1) BEFORE the dead-host breaker trips.
# Distinct from HARD_FAIL (which kills the host) — this only throttles it. conn-reset/empty-response
# already fold into CONN_REFUSED (_PATTERNS), timeouts into TIMEOUT.
WEAK_UNDER_LOAD = {CONN_REFUSED, TIMEOUT}

# ── batch-report roll-up: a persisted error_category → completion bucket ──────
# RESOLVABLE = will be retried (in-run / C3 / fresh-IP / next run). TERMINAL = unresolvable even
# after retries. Kept (error_category NULL) is handled by the caller. http_* statuses are bucketed
# via policy_for_status so 429/5xx→retryable and 404/410/400/401→terminal fall out automatically.
_TERMINAL_REASONS = {GONE_SKIP, ROBOTS, SSL, TRAP, TOO_LARGE, PARSE_ERROR, "no_main_text"}
_RETRYABLE_REASONS = {TIMEOUT, RENDER_CRASH, CONN_REFUSED, NEEDS_NETWORK_PATH,
                      HOST_DOWN, OFF_PEAK, DNS,
                      # Both are retryable because something CAN change the outcome: a warmer
                      # session or better fingerprint for a wait-only wall, a configured solver key
                      # for a widget. They are kept distinct from RENDER_CRASH so the backlog says
                      # which — "the browser died" and "a captcha stopped us" need different fixes.
                      CAPTCHA_FAILED, NEEDS_CAPTCHA_SOLVER}


def bucket_reason(reason: str | None) -> str:
    """None/'' → 'kept' (a success upsert cleared error_category). Else 'retryable' | 'terminal'."""
    if not reason:
        return "kept"
    if reason.startswith("http_"):
        try:
            pol = policy_for_status(int(reason[5:]))
        except ValueError:
            return "terminal"
        return "retryable" if pol in (RETRY_LATER, COOLDOWN) else "terminal"
    return "retryable" if reason in _RETRYABLE_REASONS else "terminal"


# What was already tried, and what would actually change the outcome. The report used to show only
# the raw reason, so "retryable" read as "we gave up on the first try" even when the full
# C1 -> impersonate -> C3 ladder had run. Keyed by reason; falls back to the raw reason.
_REASON_DETAIL = {
    NEEDS_NETWORK_PATH: ("blocked after httpx + real-Chrome JA3 + C3 stealth render all failed — "
                         "the IP is the blocker, not the browser. Needs a residential/US exit "
                         "(set CRAWLER_C3_PROXY_RETRY=1 with a proxy wired)."),
    TIMEOUT:        "host did not answer in time; retried in-run and re-queued for the next crawl.",
    CONN_REFUSED:   "host refused the connection (usually per-IP concurrency); auto-careful drops it to 1 and retries.",
    RENDER_CRASH:   "the browser render crashed; the tab was recycled and the page re-queued.",
    DNS:            "hostname did not resolve — check the URL, then the resolver.",
    HOST_DOWN:      "host was circuit-broken after repeated hard failures; retried after cooldown.",
    OFF_PEAK:       "careful .gov/.mil host outside its allowed crawl window; retried next window.",
    GONE_SKIP:      "404/410 seen twice — the page is gone. No retry will recover it.",
    ROBOTS:         "robots.txt disallows this path. Not retried by policy.",
    SSL:            "TLS trust failure. Never bypassed — a broken cert is a real trust failure.",
    TRAP:           "dropped by the frontier trap heuristic (calendar/facet explosion), never fetched.",
    TOO_LARGE:      "response exceeded the size cap; not retried.",
    PARSE_ERROR:    "fetched but could not be parsed into a document.",
    CAPTCHA_FAILED: ("a captcha was detected and the solve did not clear it. Check the recorded "
                     "captcha_type: a Cloudflare managed challenge needs a better fingerprint or a "
                     "warmer session (no token can solve it), a widget needs a working solver."),
    NEEDS_CAPTCHA_SOLVER: ("a captcha widget was detected but no solver could be used — either "
                           "CAPTCHA_PROVIDER/CAPTCHA_API_KEY is unset or the page exposed no "
                           "sitekey to build a task from. Nothing retries its way past this."),
}


def reason_detail(reason: str | None, status: int | None = None) -> str:
    """One line explaining what was already attempted and what would change the result."""
    if not reason:
        return "kept"
    if reason in _REASON_DETAIL:
        return _REASON_DETAIL[reason]
    if reason.startswith("http_"):
        kind = "retried" if bucket_reason(reason) == "retryable" else "not retried (terminal)"
        return f"server returned {reason[5:]}; {kind}."
    return reason


# ── exception / Chromium-net:: message → reason ──────────────────────────────
# Playwright exposes only error *messages* (net::ERR_*); httpx exposes exception
# text. Both are substring-matched here, first pattern wins. SSL is classified
# but the response is NEVER verify=False / ignore_https_errors — a broken cert is
# a real trust failure; we skip the page, we do not bypass it.
# ponytail: substring taxonomy; add a needle when a new failure string appears in logs.
_PATTERNS = [
    (DNS, ("getaddrinfo", "name or service not known", "nodename nor servname",
           "err_name_not_resolved", "temporary failure in name resolution")),
    (SSL, ("certificate", "ssl", "err_cert", "err_ssl", "handshake", "tlsv1", "sslv3")),
    # err_socket_not_connected / err_network_changed / err_address_unreachable were MISSING, so they
    # fell through classify_failure to an empty category: not retryable, not terminal, not
    # quarantined — the URL was simply dropped with no record of why. Found by the error_detail
    # column: five zf.com URLs carried "net::ERR_SOCKET_NOT_CONNECTED" under a NULL category.
    (CONN_REFUSED, ("connection refused", "err_connection_refused", "err_connection_closed",
                    "connection reset", "err_connection_reset", "err_empty_response",
                    "err_socket_not_connected", "err_network_changed", "err_connection_aborted",
                    "err_address_unreachable", "err_network_io_suspended", "err_socket_is_null")),
    (TIMEOUT, ("timed out", "timeout", "err_timed_out", "err_connection_timed_out",
               "deadline exceeded")),
]

# ERR_ABORTED is not a failure: Chromium aborts the navigation when the response turns out to be a
# download rather than a page. The URL is fine and the bytes are there — it is the browser that is
# the wrong tool. Kept out of _PATTERNS because the fix is to REFETCH over httpx, not to retry the
# render, and callers need to tell the two apart.
_NOT_A_PAGE = ("err_aborted", "net::err_aborted", "download is starting", "net::err_blocked_by")


def is_download_abort(error_text: str | None) -> bool:
    """True when the render failed only because the URL serves a file, not a page."""
    low = (error_text or "").lower()
    return any(n in low for n in _NOT_A_PAGE)


def classify_failure(status: int | None, error_text: str | None) -> str | None:
    """Reason for a FAILED fetch; None when the fetch succeeded (no status>=400, no error)."""
    if status is not None and status >= 400:
        return http_reason(status)
    if not error_text:
        return None
    low = error_text.lower()
    if low == ROBOTS:
        return ROBOTS
    if low == "offline_no_fixture":
        return OTHER
    for reason, needles in _PATTERNS:
        if any(n in low for n in needles):
            return reason
    if low.startswith(("render", "nav:", "content:")) or "render_failed" in low:
        return RENDER_CRASH
    return OTHER


# ── Retry-After parsing (429 / 503) ──────────────────────────────────────────
def parse_retry_after(value: str | None, cap_s: float = 300.0) -> float | None:
    """Retry-After header → seconds (delta-seconds int form OR HTTP-date). None if
    absent/unparseable. Clamped to cap_s so a hostile '31536000' can't freeze a host."""
    if not value:
        return None
    value = value.strip()
    try:
        return min(float(int(value)), cap_s)
    except ValueError:
        pass
    try:
        from datetime import datetime, timezone
        from email.utils import parsedate_to_datetime
        dt = parsedate_to_datetime(value)
        if dt is None:
            return None
        if dt.tzinfo is None:
            dt = dt.replace(tzinfo=timezone.utc)
        secs = (dt - datetime.now(timezone.utc)).total_seconds()
        return min(max(secs, 0.0), cap_s)
    except Exception:
        return None


# ── careful hosts (.gov / .mil — "quiet quiet") ──────────────────────────────
def _careful_tlds() -> set[str]:
    raw = os.environ.get("CRAWLER_CAREFUL_HOSTS", ".gov,.mil")
    return {s.strip().lstrip(".").lower() for s in raw.split(",") if s.strip()}


def is_careful_host(host: str | None) -> bool:
    """Segment-exact suffix match: epa.gov ✓, ministry.gov.in ✓, defence.mod.gov.uk ✓,
    but govtrack.us ✗ and email.com ✗ (substring, not a domain segment)."""
    if not host:
        return False
    segments = host.lower().rstrip(".").split(".")
    tlds = _careful_tlds()
    return any(seg in tlds for seg in segments)


# ── off-peak crawl window for careful hosts ──────────────────────────────────
def _parse_hours(spec: str) -> list[tuple[int, int]] | None:
    """'0-6,20-23' → [(0,6),(20,23)]. 'off'/'' → None (always allowed)."""
    spec = (spec or "").strip().lower()
    if not spec or spec == "off":
        return None
    ranges: list[tuple[int, int]] = []
    for part in spec.split(","):
        if "-" not in part:
            continue
        a, b = part.split("-", 1)
        try:
            ranges.append((int(a) % 24, int(b) % 24))
        except ValueError:
            continue
    return ranges or None


def in_allowed_window(hour: int, spec: str) -> bool:
    """Is `hour` (0-23) inside the allowed spec? Ranges may wrap midnight (20-6)."""
    ranges = _parse_hours(spec)
    if ranges is None:
        return True
    for a, b in ranges:
        if a <= b:
            if a <= hour <= b:
                return True
        elif hour >= a or hour <= b:      # wraps midnight
            return True
    return False


def careful_off_peak_now(host: str | None) -> bool:
    """True when `host` is careful AND the current LOCAL hour is OUTSIDE
    CRAWLER_CAREFUL_HOURS — the URL should be skipped now and retried next run
    (polite: don't hammer a gov server during its business/peak hours)."""
    if not is_careful_host(host):
        return False
    spec = os.environ.get("CRAWLER_CAREFUL_HOURS", "off")
    from datetime import datetime
    return not in_allowed_window(datetime.now().hour, spec)


# ── URL trap heuristics (stateless, cheap) ───────────────────────────────────
def looks_like_trap(canon_url: str) -> str | None:
    """Cheap stateless URL-shape trap checks → TRAP or None. The STATEFUL
    query-explosion cap (calendar/facet traps) lives at the enqueue site — it
    needs per-job (host,path)->count state that doesn't belong in a pure function."""
    from urllib.parse import urlsplit

    if len(canon_url) > _env_int("CRAWLER_MAX_URL_LEN", 2000):
        return TRAP
    segs = [s for s in urlsplit(canon_url).path.split("/") if s]
    if len(segs) > 12:
        return TRAP
    counts: dict[str, int] = {}
    for s in segs:                       # /a/b/a/b/a/b … loop trap
        counts[s] = counts.get(s, 0) + 1
        if counts[s] >= 3:
            return TRAP
    return None
